# Generated by Django 2.2.1 on 2019-06-12 02:00

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Floor',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('floor_name', models.CharField(max_length=20, verbose_name='フロア名')),
                ('floor_no', models.IntegerField(verbose_name='フロア番号')),
            ],
        ),
        migrations.CreateModel(
            name='Map',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('map_name', models.CharField(max_length=20, verbose_name='地図名称')),
                ('map_no', models.IntegerField(default=-1, verbose_name='地図番号')),
            ],
        ),
        migrations.CreateModel(
            name='Room',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('room_name', models.CharField(max_length=20, verbose_name='個室名')),
                ('room_no', models.IntegerField(default=-1, verbose_name='個室番号')),
                ('floor_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='iotoiletapp.Floor')),
            ],
        ),
        migrations.CreateModel(
            name='RoomType',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('room_type_name', models.CharField(max_length=20, verbose_name='個室タイプ')),
                ('room_type_no', models.IntegerField(default=-1, verbose_name='個室タイプ番号')),
            ],
        ),
        migrations.CreateModel(
            name='SensorStatusType',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sensor_status_type_name', models.CharField(max_length=20, verbose_name='センサー状態タイプ名')),
                ('sensor_status_type_no', models.IntegerField(default=-1, verbose_name='センサー状態タイプ番号')),
            ],
        ),
        migrations.CreateModel(
            name='SensorType',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sensor_type_name', models.CharField(max_length=20, verbose_name='センサータイプ名')),
                ('sensor_type_no', models.IntegerField(default=-1, verbose_name='センサータイプ番号')),
            ],
        ),
        migrations.CreateModel(
            name='Sex',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sex_name', models.CharField(max_length=20, verbose_name='性別名')),
                ('sex_no', models.IntegerField(default=-1, verbose_name='性別番号')),
            ],
        ),
        migrations.CreateModel(
            name='Toilet',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('toilet_name', models.CharField(max_length=20, verbose_name='トイレ名')),
                ('toilet_no', models.IntegerField(default=-1, verbose_name='トイレ番号')),
                ('is_wheelchair', models.IntegerField(default=1, verbose_name='車いす')),
                ('brightness_threshold', models.IntegerField(default=1, verbose_name='明るさ閾値')),
                ('map_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='iotoiletapp.Map')),
                ('room_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='iotoiletapp.Room')),
            ],
        ),
        migrations.CreateModel(
            name='ToiletStatsuHist',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('toilet_name', models.CharField(max_length=20, verbose_name='トイレ名')),
                ('toilet_no', models.IntegerField(default=-1, verbose_name='トイレ番号')),
                ('is_wheelchair', models.IntegerField(default=-1, verbose_name='車いす')),
                ('room_name', models.CharField(max_length=20, verbose_name='個室名')),
                ('room_no', models.IntegerField(default=-1, verbose_name='個室番号')),
                ('floor_name', models.CharField(max_length=20, verbose_name='フロア名')),
                ('floor_no', models.IntegerField(verbose_name='フロア番号')),
                ('sex_name', models.CharField(max_length=20, verbose_name='性別名')),
                ('sex_no', models.IntegerField(default=-1, verbose_name='性別番号')),
                ('map_name', models.CharField(max_length=20, verbose_name='地図名称')),
                ('map_no', models.IntegerField(default=-1, verbose_name='地図番号')),
                ('toilet_status_type_name', models.CharField(max_length=20, verbose_name='個室状況名称')),
                ('toilet_status_type_no', models.IntegerField(default=-1, verbose_name='個室状況番号')),
                ('timestamp', models.DateTimeField(verbose_name='登録時刻')),
            ],
        ),
        migrations.CreateModel(
            name='ToiletStatusType',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('toilet_status_type_name', models.CharField(max_length=20, verbose_name='個室状況名称')),
                ('toilet_status_type_no', models.IntegerField(default=-1, verbose_name='個室状況番号')),
            ],
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_id', models.CharField(max_length=20, verbose_name='ユーザID')),
                ('password', models.CharField(max_length=20, verbose_name='パスワード')),
                ('user_name', models.CharField(max_length=20, verbose_name='ユーザ名')),
                ('floor_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='iotoiletapp.Floor')),
                ('sex', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='iotoiletapp.Sex')),
            ],
        ),
        migrations.CreateModel(
            name='SexRoomType',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('room_type_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='iotoiletapp.RoomType')),
                ('sex_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='iotoiletapp.Sex')),
            ],
            options={
                'unique_together': {('room_type_id', 'sex_id')},
            },
        ),
        migrations.CreateModel(
            name='Sensor',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sensor_name', models.CharField(max_length=20, verbose_name='センサー名')),
                ('sensor_no', models.IntegerField(default=-1, verbose_name='センサー番号')),
                ('sensor_status_type_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='iotoiletapp.SensorStatusType')),
                ('sensor_type_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='iotoiletapp.SensorType')),
                ('toilet_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='iotoiletapp.Toilet')),
            ],
        ),
        migrations.AddField(
            model_name='room',
            name='room_type_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='iotoiletapp.SexRoomType'),
        ),
        migrations.CreateModel(
            name='ToiletStatus',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('timestamp', models.DateTimeField(verbose_name='登録時刻')),
                ('toilet_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='iotoiletapp.Toilet')),
                ('toilet_status_type_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='iotoiletapp.ToiletStatusType')),
            ],
            options={
                'unique_together': {('timestamp', 'toilet_id')},
            },
        ),
        migrations.CreateModel(
            name='SensorData',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('value1', models.CharField(max_length=20, verbose_name='センサー値1')),
                ('value2', models.CharField(max_length=20, verbose_name='センサー値2')),
                ('value3', models.CharField(max_length=20, verbose_name='センサー値3')),
                ('value4', models.CharField(max_length=20, verbose_name='センサー値4')),
                ('value5', models.CharField(max_length=20, verbose_name='センサー値5')),
                ('sensor_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='iotoiletapp.Sensor')),
            ],
            options={
                'unique_together': {('timestamp', 'sensor_id')},
            },
        ),
    ]
