# Generated by Django 2.2.1 on 2019-06-12 04:48

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('iotoiletapp', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='room',
            name='floor_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='iotoiletapp.Floor'),
        ),
        migrations.AlterField(
            model_name='room',
            name='room_type_id',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='iotoiletapp.SexRoomType'),
        ),
        migrations.AlterField(
            model_name='sensor',
            name='sensor_status_type_id',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='iotoiletapp.SensorStatusType'),
        ),
        migrations.AlterField(
            model_name='sensor',
            name='sensor_type_id',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='iotoiletapp.SensorType'),
        ),
        migrations.AlterField(
            model_name='sensor',
            name='toilet_id',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='iotoiletapp.Toilet'),
        ),
        migrations.AlterField(
            model_name='sensordata',
            name='sensor_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='iotoiletapp.Sensor'),
        ),
        migrations.AlterField(
            model_name='toilet',
            name='map_id',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='iotoiletapp.Map'),
        ),
        migrations.AlterField(
            model_name='toilet',
            name='room_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='iotoiletapp.Room'),
        ),
        migrations.AlterField(
            model_name='toiletstatus',
            name='toilet_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='iotoiletapp.Toilet'),
        ),
        migrations.AlterField(
            model_name='toiletstatus',
            name='toilet_status_type_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='iotoiletapp.ToiletStatusType'),
        ),
        migrations.AlterField(
            model_name='user',
            name='floor_id',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='iotoiletapp.Floor'),
        ),
        migrations.AlterField(
            model_name='user',
            name='sex',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='iotoiletapp.Sex'),
        ),
    ]
