# Generated by Django 2.2.1 on 2019-06-12 05:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('iotoiletapp', '0002_auto_20190612_1348'),
    ]

    operations = [
        migrations.AddField(
            model_name='sexroomtype',
            name='sex_room_type_name',
            field=models.CharField(max_length=20, null=True, verbose_name='性別個室対応名'),
        ),
    ]
