# Generated by Django 2.2.1 on 2019-06-12 07:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('iotoiletapp', '0003_sexroomtype_sex_room_type_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sensordata',
            name='value1',
            field=models.CharField(blank=True, max_length=20, verbose_name='センサー値1'),
        ),
        migrations.AlterField(
            model_name='sensordata',
            name='value2',
            field=models.CharField(blank=True, max_length=20, verbose_name='センサー値2'),
        ),
        migrations.AlterField(
            model_name='sensordata',
            name='value3',
            field=models.CharField(blank=True, max_length=20, verbose_name='センサー値3'),
        ),
        migrations.AlterField(
            model_name='sensordata',
            name='value4',
            field=models.CharField(blank=True, max_length=20, verbose_name='センサー値4'),
        ),
        migrations.AlterField(
            model_name='sensordata',
            name='value5',
            field=models.CharField(blank=True, max_length=20, verbose_name='センサー値5'),
        ),
    ]
