# Generated by Django 2.2.1 on 2019-06-12 07:42

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('iotoiletapp', '0004_auto_20190612_1610'),
    ]

    operations = [
        migrations.AlterField(
            model_name='room',
            name='room_type_id',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='iotoiletapp.RoomType'),
        ),
    ]
